-- 01_schema.sql
-- Create database and base table.
CREATE DATABASE IF NOT EXISTS banking_credit_risk;
USE banking_credit_risk;

-- SCHEMA01 | One row per customer
CREATE TABLE IF NOT EXISTS credit_clients_raw (
    ID INT PRIMARY KEY,
    LIMIT_BAL DECIMAL(14,2), SEX INT, EDUCATION INT, MARRIAGE INT, AGE INT,
    PAY_0 INT, PAY_2 INT, PAY_3 INT, PAY_4 INT, PAY_5 INT, PAY_6 INT,
    BILL_AMT1 DECIMAL(14,2), BILL_AMT2 DECIMAL(14,2), BILL_AMT3 DECIMAL(14,2),
    BILL_AMT4 DECIMAL(14,2), BILL_AMT5 DECIMAL(14,2), BILL_AMT6 DECIMAL(14,2),
    PAY_AMT1 DECIMAL(14,2), PAY_AMT2 DECIMAL(14,2), PAY_AMT3 DECIMAL(14,2),
    PAY_AMT4 DECIMAL(14,2), PAY_AMT5 DECIMAL(14,2), PAY_AMT6 DECIMAL(14,2),
    DefaultFlag TINYINT
);


-- SCHEMA02 | LOCAL INFILE must be enabled for LOAD DATA LOCAL INFILE
SHOW VARIABLES LIKE 'local_infile';

show tables;

DESCRIBE credit_clients_raw;
